### ISSUE TITLE
Too wide str_replace

### ISSUE THREAD

**Issue by Globov** [MXCCoin/MXCore#22]
https://github.com/MXCCoin/MXCore/blob/faea71a896641cdacc36e3dbe3e5d7190c7a5d33/src/Tools.php#L293

Webserver home path can be anything, and can include legit things containing "cli" (or any other of the words there).
For instance, on standard isp config setups (widely used open source control panel)
home path are like `/var/www/clients/client1/web1/...`

That is then converted to  `/var/www/ents/ent1/web1/...` and does not work.

This string needs a more specific handling.

**Comment by mataxetos** [comment]
Thanks for the report, I will solve it in the next pull request

**Comment by mataxetos** [comment]
Fix prepared for the next update https://github.com/MXCCoin/MXCore/commit/195dbfb403d33dbaf458ee821a88ed85f6ee102b#diff-5a33b32a759b88d71a3a5a3416cd8615
